autoload:

  # only for ioncube
  
  ioncube_project:
    name:        ioncube project
    files:
      Text_Diff_Engine_xdiff: %SF_LIB_DIR%/Text/Diff/Engine/xdiff.php
      Text_Diff_Engine_native: %SF_LIB_DIR%/Text/Diff/Engine/native.php
      Text_Diff_Engine_string: %SF_LIB_DIR%/Text/Diff/Engine/string.php
      Text_Diff_Engine_shell: %SF_LIB_DIR%/Text/Diff/Engine/shell.php
      Text_Diff_Renderer_inline: %SF_LIB_DIR%/Text/Diff/Renderer/inline.php
      Text_Diff_Renderer_unified: %SF_LIB_DIR%/Text/Diff/Renderer/unified.php
      Text_Diff_Renderer_context: %SF_LIB_DIR%/Text/Diff/Renderer/context.php
      Text_Diff_Renderer: %SF_LIB_DIR%/Text/Diff/Renderer.php
      Text_Diff3: %SF_LIB_DIR%/Text/Diff3.php
      Text_Diff3_Op: %SF_LIB_DIR%/Text/Diff3.php
      Text_Diff3_Op_copy: %SF_LIB_DIR%/Text/Diff3.php
      Text_Diff3_BlockBuilder: %SF_LIB_DIR%/Text/Diff3.php
      Text_Diff: %SF_LIB_DIR%/Text/Diff.php
      Text_MappedDiff: %SF_LIB_DIR%/Text/Diff.php
      Text_Diff_Op: %SF_LIB_DIR%/Text/Diff.php
      Text_Diff_Op_copy: %SF_LIB_DIR%/Text/Diff.php
      Text_Diff_Op_delete: %SF_LIB_DIR%/Text/Diff.php
      Text_Diff_Op_add: %SF_LIB_DIR%/Text/Diff.php
      Text_Diff_Op_change: %SF_LIB_DIR%/Text/Diff.php
      upload: %SF_LIB_DIR%/upload/class.upload.php
      Net_Portscan: %SF_LIB_DIR%/Net/Portscan.php
      sfHostAddressValidator: %SF_LIB_DIR%/sfHostAddressValidator.class.php
  
  ioncube_project_model:
    name:        ioncube project model
    files:
      HostGroup: %SF_MODEL_LIB_DIR%/HostGroup.php
      HostPeer: %SF_MODEL_LIB_DIR%/HostPeer.php
      ServiceToHost: %SF_MODEL_LIB_DIR%/ServiceToHost.php
      CommandPeer: %SF_MODEL_LIB_DIR%/CommandPeer.php
      Contact: %SF_MODEL_LIB_DIR%/Contact.php
      Host: %SF_MODEL_LIB_DIR%/Host.php
      HostServiceParamPeer: %SF_MODEL_LIB_DIR%/HostServiceParamPeer.php
      OsPeer: %SF_MODEL_LIB_DIR%/OsPeer.php
      Service: %SF_MODEL_LIB_DIR%/Service.php
      HostToContactGroup: %SF_MODEL_LIB_DIR%/HostToContactGroup.php
      HostGroupPeer: %SF_MODEL_LIB_DIR%/HostGroupPeer.php
      ContactPeer: %SF_MODEL_LIB_DIR%/ContactPeer.php
      ContactGroup: %SF_MODEL_LIB_DIR%/ContactGroup.php
      ServiceToHostPeer: %SF_MODEL_LIB_DIR%/ServiceToHostPeer.php
      GroupToContact: %SF_MODEL_LIB_DIR%/GroupToContact.php
      Template: %SF_MODEL_LIB_DIR%/Template.php
      ServicePeer: %SF_MODEL_LIB_DIR%/ServicePeer.php
      BaseContactPeer: %SF_MODEL_LIB_DIR%/om/BaseContactPeer.php
      BaseService: %SF_MODEL_LIB_DIR%/om/BaseService.php
      BaseHostToContactGroup: %SF_MODEL_LIB_DIR%/om/BaseHostToContactGroup.php
      BaseServiceToHost: %SF_MODEL_LIB_DIR%/om/BaseServiceToHost.php
      BaseHostGroupPeer: %SF_MODEL_LIB_DIR%/om/BaseHostGroupPeer.php
      BaseContactGroup: %SF_MODEL_LIB_DIR%/om/BaseContactGroup.php
      BaseServiceToHostPeer: %SF_MODEL_LIB_DIR%/om/BaseServiceToHostPeer.php
      BaseGroupToContact: %SF_MODEL_LIB_DIR%/om/BaseGroupToContact.php
      BaseTemplate: %SF_MODEL_LIB_DIR%/om/BaseTemplate.php
      BaseServicePeer: %SF_MODEL_LIB_DIR%/om/BaseServicePeer.php
      BaseHost: %SF_MODEL_LIB_DIR%/om/BaseHost.php
      BaseTemplatePeer: %SF_MODEL_LIB_DIR%/om/BaseTemplatePeer.php
      BaseCommand: %SF_MODEL_LIB_DIR%/om/BaseCommand.php
      BaseOs: %SF_MODEL_LIB_DIR%/om/BaseOs.php
      BaseHostServiceParam: %SF_MODEL_LIB_DIR%/om/BaseHostServiceParam.php
      BaseGroupToContactPeer: %SF_MODEL_LIB_DIR%/om/BaseGroupToContactPeer.php
      BaseContactGroupPeer: %SF_MODEL_LIB_DIR%/om/BaseContactGroupPeer.php
      BaseHostToContactGroupPeer: %SF_MODEL_LIB_DIR%/om/BaseHostToContactGroupPeer.php
      BaseHostPeer: %SF_MODEL_LIB_DIR%/om/BaseHostPeer.php
      BaseHostGroup: %SF_MODEL_LIB_DIR%/om/BaseHostGroup.php
      BaseCommandPeer: %SF_MODEL_LIB_DIR%/om/BaseCommandPeer.php
      BaseHostServiceParamPeer: %SF_MODEL_LIB_DIR%/om/BaseHostServiceParamPeer.php
      BaseContact: %SF_MODEL_LIB_DIR%/om/BaseContact.php
      BaseGroupToHost: %SF_MODEL_LIB_DIR%/om/BaseGroupToHost.php
      BaseOsPeer: %SF_MODEL_LIB_DIR%/om/BaseOsPeer.php
      HostToContactGroupMapBuilder: %SF_MODEL_LIB_DIR%/map/HostToContactGroupMapBuilder.php
      ContactGroupMapBuilder: %SF_MODEL_LIB_DIR%/map/ContactGroupMapBuilder.php
      GroupToContactMapBuilder: %SF_MODEL_LIB_DIR%/map/GroupToContactMapBuilder.php
      HostGroupMapBuilder: %SF_MODEL_LIB_DIR%/map/HostGroupMapBuilder.php
      ContactMapBuilder: %SF_MODEL_LIB_DIR%/map/ContactMapBuilder.php
      ServiceToHostMapBuilder: %SF_MODEL_LIB_DIR%/map/ServiceToHostMapBuilder.php
      TemplateMapBuilder: %SF_MODEL_LIB_DIR%/map/TemplateMapBuilder.php
      HostMapBuilder: %SF_MODEL_LIB_DIR%/map/HostMapBuilder.php
      CommandMapBuilder: %SF_MODEL_LIB_DIR%/map/CommandMapBuilder.php
      ServiceMapBuilder: %SF_MODEL_LIB_DIR%/map/ServiceMapBuilder.php
      HostServiceParamMapBuilder: %SF_MODEL_LIB_DIR%/map/HostServiceParamMapBuilder.php
      OsMapBuilder: %SF_MODEL_LIB_DIR%/map/OsMapBuilder.php
      Command: %SF_MODEL_LIB_DIR%/Command.php
      Os: %SF_MODEL_LIB_DIR%/Os.php
      HostServiceParam: %SF_MODEL_LIB_DIR%/HostServiceParam.php
      GroupToContactPeer: %SF_MODEL_LIB_DIR%/GroupToContactPeer.php
      ContactGroupPeer: %SF_MODEL_LIB_DIR%/ContactGroupPeer.php
      HostToContactGroupPeer: %SF_MODEL_LIB_DIR%/HostToContactGroupPeer.php
      TemplatePeer: %SF_MODEL_LIB_DIR%/TemplatePeer.php
  
  ioncube_application:
    name:        ioncube application
    files:
      myUser:    %SF_APP_LIB_DIR%/myUser.class.php

#  ioncube_module:
#    name:        ioncube module
#    files:
