#dev:
#  layout:         layout_dev

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Nagios Administrator
    robots:       index, follow
    description:  Nagios Administrator
    keywords:     nagios, administrator
    language:     en

  stylesheets:    [main, styles: { position: last }]

  javascripts:    []

  has_layout:     true
  layout:         layout
