generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Command
    theme:            default
    
    fields:
      command_summary: { name: Command }

    list:
      title:   Commands
      display: [ =name, command_summary ]
      filters: [ name ]
      object_actions:
        _edit:        ~
        _delete:      ~

    edit:
      fields:
        created_at:   { type: plain }
        updated_at:   { type: plain }
        command:      { type: input_tag, params: size=80 }
        nagios_help:  { name: Nagios help }

      display:
        "NONE":                   [ name, command, _nagios_help ]
        "Information":            [ created_at, updated_at ]
