generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Service
    theme:            default

    list:
      title:   Services
      display: [ =name, alias, port ]
      filters: [ name, alias, port ]
      object_actions:
        _edit:        ~
        _delete:      ~
    
    edit:
      fields:
        special:      { type: textarea_tag, params: cols=80 rows=10 class=fixed }
        hosts:        { type: admin_check_list, params: through_class=ServiceToHost }
        created_at:   { type: plain }
        updated_at:   { type: plain }
      display:
        "NONE":                   [ name, alias, command_id, port, special ]
        "Hosts":                  [ hosts ]
        "Information":            [ created_at, updated_at ]
        