generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Template
    theme:            default

    fields:
      content_summary: { name: Content }

    list:
      title:   Templates
      display: [ =name, alias, content_summary ]
      filters: [ name, alias, content ]
      object_actions:
        _edit:        ~
        _delete:      ~

    edit:
      fields:
        content:      { type: textarea_tag, params: cols=80 rows=10 class=fixed }
        created_at:   { type: plain }
        updated_at:   { type: plain }
      display:
        "NONE":                   [ _type, name, alias, content ]
        "Information":            [ created_at, updated_at ]
        