generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Host
    theme:            default

    fields:
      os_id:          { name: Operating System }
#      services:       { help: When deselecting any service the command parameters get lost! }

    list:
      title:          Hosts
      display:        [ =name, alias, address, group_name]
      filters:        [ name, alias, address ]
      object_actions:
        _edit:        ~
        _delete:      ~
        params:       { name: Customize host services, action: serviceparameters, icon: backend/wrench_orange.png }

    edit:
      fields:
        services:     { type: admin_check_list, params: through_class=ServiceToHost }
        contactgroups:     { type: admin_check_list, params: through_class=HostToContactGroup }
        created_at:   { type: plain }
        updated_at:   { type: plain }
        os_id:        { params: include_custom=Choose... }
        special:      { type: textarea_tag, params: cols=80 rows=10 class=fixed }
        nagios_help:  { name: Nagios help }
      display:
        "NONE":       [ name, alias, address, group_id, os_id, contactgroups, special, _nagios_help ]
        "Services":   [ services, _portscan, _serviceparameters ]
        "Information":[ created_at, updated_at ]
