#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root:@localhost/dbname
prod:
  propel:
    param:
      host:               localhost

dev:
  propel:
    param:
      classname:          DebugPDO

test:
  propel:
    param:
      classname:          DebugPDO

all:
  propel:
    class:                sfPropelDatabase
    param:
      dsn:        mysql:dbname=nagiosadmin;host=localhost
      username:   root
      password:
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
